language: objective-c

branches:
  only:
    - master

xcode_workspace: OND.xcworkspace
xcode_scheme: OND-Example
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild test -workspace Example/OND.xcworkspace -scheme OND-Example -destination "platform=iOS Simulator,name=iPhone 6s"